# Generated by Django 4.1.1 on 2023-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileicon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iconset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
